import * as CONST from './Constants';
import * as FUNC from './Common_Functions';

const HEAVY_CONCRETE_COMPRESSION_STRENGTH_CLASSES = ['B3,5', 'B5', 'B7,5', 'B10', 'B12,5', 'B15', 'B20', 'B25', 'B30', 'B35', 'B40', 'B45', 'B50', 'B55', 'B60', 'B70', 'B80', 'B90', 'B100'];
const PRESTRESSED_CONCRETE_COMPRESSION_STRENGTH_CLASSES = ['B20', 'B25', 'B30', 'B35', 'B40', 'B45', 'B50', 'B55', 'B60', 'B70'];
const FINE_GRAIN_CONCRETE_GROUP_A_COMPRESSION_STRENGTH_CLASSES = ['B3,5', 'B5', 'B7,5', 'B10', 'B12,5', 'B15', 'B20', 'B25', 'B30', 'B35', 'B40'];
const FINE_GRAIN_CONCRETE_GROUP_B_COMPRESSION_STRENGTH_CLASSES = ['B15', 'B20', 'B25', 'B30', 'B35', 'B40', 'B45', 'B50', 'B55', 'B60'];

let LIGHT_CONCRETE_COMPRESSION_STRENGTH_CLASSES = {};
LIGHT_CONCRETE_COMPRESSION_STRENGTH_CLASSES ['D800'] = ['B2,5', 'B3,5', 'B5', 'B7,5'];
LIGHT_CONCRETE_COMPRESSION_STRENGTH_CLASSES ['D900'] = LIGHT_CONCRETE_COMPRESSION_STRENGTH_CLASSES ['D800'];
LIGHT_CONCRETE_COMPRESSION_STRENGTH_CLASSES ['D1000'] = ['B2,5', 'B3,5', 'B5', 'B7,5', 'B10', 'B12,5'];
LIGHT_CONCRETE_COMPRESSION_STRENGTH_CLASSES ['D1100'] = LIGHT_CONCRETE_COMPRESSION_STRENGTH_CLASSES ['D1000'];
LIGHT_CONCRETE_COMPRESSION_STRENGTH_CLASSES ['D1200'] = ['B2,5', 'B3,5', 'B5', 'B7,5', 'B10', 'B12,5', 'B15', 'B20'];
LIGHT_CONCRETE_COMPRESSION_STRENGTH_CLASSES ['D1300'] = LIGHT_CONCRETE_COMPRESSION_STRENGTH_CLASSES ['D1200'];
LIGHT_CONCRETE_COMPRESSION_STRENGTH_CLASSES ['D1400'] = ['B3,5', 'B5', 'B7,5', 'B10', 'B12,5', 'B15', 'B20', 'B25', 'B30'];
LIGHT_CONCRETE_COMPRESSION_STRENGTH_CLASSES ['D1500'] = LIGHT_CONCRETE_COMPRESSION_STRENGTH_CLASSES ['D1400'];
LIGHT_CONCRETE_COMPRESSION_STRENGTH_CLASSES ['D1600'] = ['B7,5', 'B10', 'B12,5', 'B15', 'B20', 'B25', 'B30', 'B35', 'B40'];
LIGHT_CONCRETE_COMPRESSION_STRENGTH_CLASSES ['D1700'] = LIGHT_CONCRETE_COMPRESSION_STRENGTH_CLASSES ['D1600'];
LIGHT_CONCRETE_COMPRESSION_STRENGTH_CLASSES ['D1800'] = ['B15', 'B20', 'B25', 'B30', 'B35', 'B40'];
LIGHT_CONCRETE_COMPRESSION_STRENGTH_CLASSES ['D1900'] = LIGHT_CONCRETE_COMPRESSION_STRENGTH_CLASSES ['D1800'];
LIGHT_CONCRETE_COMPRESSION_STRENGTH_CLASSES ['D2000'] = ['B25', 'B30', 'B35', 'B40'];

let POROUS_CONCRETE_COMPRESSION_STRENGTH_CLASSES = {};
POROUS_CONCRETE_COMPRESSION_STRENGTH_CLASSES['D800'] = ['B2,5', 'B3,5', 'B5'];
POROUS_CONCRETE_COMPRESSION_STRENGTH_CLASSES['D900'] = POROUS_CONCRETE_COMPRESSION_STRENGTH_CLASSES['D800'];
POROUS_CONCRETE_COMPRESSION_STRENGTH_CLASSES['D1000'] = POROUS_CONCRETE_COMPRESSION_STRENGTH_CLASSES['D800'];
POROUS_CONCRETE_COMPRESSION_STRENGTH_CLASSES['D1100'] = ['B7,5'];
POROUS_CONCRETE_COMPRESSION_STRENGTH_CLASSES['D1200'] = POROUS_CONCRETE_COMPRESSION_STRENGTH_CLASSES['D1100'];
POROUS_CONCRETE_COMPRESSION_STRENGTH_CLASSES['D1300'] = POROUS_CONCRETE_COMPRESSION_STRENGTH_CLASSES['D1100'];
POROUS_CONCRETE_COMPRESSION_STRENGTH_CLASSES['D1400'] = ['B3,5', 'B5', 'B7,5'];

let CELL_AUTOCLAVE_CONCRETE_COMPRESSION_STRENGTH_CLASSES = {};
CELL_AUTOCLAVE_CONCRETE_COMPRESSION_STRENGTH_CLASSES['D500'] = ['B1,5', 'B2', 'B2,5'];
CELL_AUTOCLAVE_CONCRETE_COMPRESSION_STRENGTH_CLASSES['D600'] = ['B1,5', 'B2', 'B2,5', 'B3,5'];
CELL_AUTOCLAVE_CONCRETE_COMPRESSION_STRENGTH_CLASSES['D700'] = ['B2', 'B2,5', 'B3,5', 'B5'];
CELL_AUTOCLAVE_CONCRETE_COMPRESSION_STRENGTH_CLASSES['D800'] = ['B2,5', 'B3,5', 'B5', 'B7,5'];
CELL_AUTOCLAVE_CONCRETE_COMPRESSION_STRENGTH_CLASSES['D900'] = ['B3,5', 'B5', 'B7,5', 'B10'];
CELL_AUTOCLAVE_CONCRETE_COMPRESSION_STRENGTH_CLASSES['D1000'] = ['B7,5', 'B10', 'B12,5'];
CELL_AUTOCLAVE_CONCRETE_COMPRESSION_STRENGTH_CLASSES['D1100'] = ['B10', 'B12,5', 'B15', 'B17,5'];
CELL_AUTOCLAVE_CONCRETE_COMPRESSION_STRENGTH_CLASSES['D1200'] = ['B12,5', 'B15', 'B17,5', 'B20'];

let CELL_CONCRETE_COMPRESSION_STRENGTH_CLASSES = {};
CELL_CONCRETE_COMPRESSION_STRENGTH_CLASSES['D600'] = ['B1,5', 'B2'];
CELL_CONCRETE_COMPRESSION_STRENGTH_CLASSES['D700'] = ['B1,5', 'B2', 'B2,5'];
CELL_CONCRETE_COMPRESSION_STRENGTH_CLASSES['D800'] = ['B2', 'B2,5', 'B3,5'];
CELL_CONCRETE_COMPRESSION_STRENGTH_CLASSES['D900'] = ['B2,5', 'B3,5', 'B5'];
CELL_CONCRETE_COMPRESSION_STRENGTH_CLASSES['D1000'] = ['B5', 'B7,5'];
CELL_CONCRETE_COMPRESSION_STRENGTH_CLASSES['D1100'] = ['B7,5', 'B10'];
CELL_CONCRETE_COMPRESSION_STRENGTH_CLASSES['D1200'] = ['B10', 'B12,5'];

let defaultValidationProperties = {"type": "number", "minimum": 0};

let schema = {
    "type": "object",
    "properties": {
        [CONST.VAR_CONCRETE_TYPE]: {
            "oneOf": [
                {"const": CONST.HEAVY_CONCRETE},
                {"const": CONST.PRESTRESSED_CONCRETE},
                {"const": CONST.FINE_GRAIN_HEATED_CONCRETE_GROUP_A},
                {"const": CONST.FINE_GRAIN_NOT_HEATED_CONCRETE_GROUP_A},
                {"const": CONST.FINE_GRAIN_AUTOCLAVE_CONCRETE_GROUP_B},
                {"const": CONST.LIGHT_CONCRETE},
                {"const": CONST.POROUS_CONCRETE},
                {"const": CONST.CELL_AUTOCLAVE_CONCRETE},
                {"const": CONST.CELL_CONCRETE},
            ]
        },
        [CONST.VAR_CONCRETE_DENSITY]: {"type": "string"},

    },
    "required": [
        CONST.VAR_CONCRETE_TYPE
    ]
};

function calculate(obj) {
    if (obj[CONST.VAR_CONCRETE_TYPE] === CONST.HEAVY_CONCRETE)  {return HEAVY_CONCRETE_COMPRESSION_STRENGTH_CLASSES;}
    if (obj[CONST.VAR_CONCRETE_TYPE] === CONST.PRESTRESSED_CONCRETE)  {return PRESTRESSED_CONCRETE_COMPRESSION_STRENGTH_CLASSES;}
    if (obj[CONST.VAR_CONCRETE_TYPE] === CONST.FINE_GRAIN_HEATED_CONCRETE_GROUP_A || obj[CONST.VAR_CONCRETE_TYPE]===CONST.FINE_GRAIN_NOT_HEATED_CONCRETE_GROUP_A)  {return FINE_GRAIN_CONCRETE_GROUP_A_COMPRESSION_STRENGTH_CLASSES;}
    if (obj[CONST.VAR_CONCRETE_TYPE] === CONST.FINE_GRAIN_AUTOCLAVE_CONCRETE_GROUP_B)  {return FINE_GRAIN_CONCRETE_GROUP_B_COMPRESSION_STRENGTH_CLASSES;}

    if (obj[CONST.VAR_CONCRETE_DENSITY] !== null) {

        if (obj[CONST.VAR_CONCRETE_TYPE] === CONST.LIGHT_CONCRETE) {
            if (obj[CONST.VAR_CONCRETE_DENSITY] in LIGHT_CONCRETE_COMPRESSION_STRENGTH_CLASSES) {
                return LIGHT_CONCRETE_COMPRESSION_STRENGTH_CLASSES[obj[CONST.VAR_CONCRETE_DENSITY]];
            }
        }
        if (obj[CONST.VAR_CONCRETE_TYPE] === CONST.POROUS_CONCRETE) {
            if (obj[CONST.VAR_CONCRETE_DENSITY] in POROUS_CONCRETE_COMPRESSION_STRENGTH_CLASSES) {
                return POROUS_CONCRETE_COMPRESSION_STRENGTH_CLASSES[obj[CONST.VAR_CONCRETE_DENSITY]];
            }
        }

        if (obj[CONST.VAR_CONCRETE_TYPE] === CONST.CELL_AUTOCLAVE_CONCRETE) {
            if (obj[CONST.VAR_CONCRETE_DENSITY] in CELL_AUTOCLAVE_CONCRETE_COMPRESSION_STRENGTH_CLASSES) {
                return CELL_AUTOCLAVE_CONCRETE_COMPRESSION_STRENGTH_CLASSES[obj[CONST.VAR_CONCRETE_DENSITY]];
            }
        }

        if (obj[CONST.VAR_CONCRETE_TYPE] === CONST.CELL_CONCRETE) {
            if (obj[CONST.VAR_CONCRETE_DENSITY] in CELL_CONCRETE_COMPRESSION_STRENGTH_CLASSES) {
                return CELL_CONCRETE_COMPRESSION_STRENGTH_CLASSES[obj[CONST.VAR_CONCRETE_DENSITY]];
            }
        }
    }

    return null;
}

export default function (json) {
    return FUNC.prepareFeedbackObject(schema, defaultValidationProperties, json, calculate);
}